export const GET_TRAINS: "GET_TRAINS" = "GET_TRAINS";
export const POST_TRAINS: "POST_TRAINS" = "POST_TRAINS";
export const CLOSE_MODAL: "CLOSE_MODAL" = "CLOSE_MODAL";
export const SHOW_TRAIN: "SHOW_TRAIN" = "SHOW_TRAIN";
